### ISSUE TITLE
Not able to load the radiopush home page on local dev machine

### ISSUE THREAD

**Issue by mazz** [puemos/radiopush#14]
Running Radiopush on my development machine but I am blocked because despite having a SPOTIFY_CLIENT_ID and SPOTIFY_CLIENT_SECRET and login I get an error from Spotify that my localhost:4000...Client redirect URI is invalid.

## Steps:
- source SPOTIFY_CLIENT_ID to env vars
- source SPOTIFY_CLIENT_SECRET to env vars
- `cd assets; npm install; cd ..`
- `mix deps.get`
- `mix ecto.reset`
- `mix phx.server`

open localhost:4000 in browser, click Sign In
Spotify returns in browser: "Client Redirect URI is invalid.

Not able to load the radiopush home page.

**Comment by puemos** [comment]
@mazz you need to make sure that in your [Spotify app](https://developer.spotify.com/dashboard/applications) you added the local redirect (http://localhost:4000/auth/spotify/callback)
![image](https://user-images.githubusercontent.com/13174025/129241288-1d47cfed-3c4b-4238-bb2d-6ac5293855dd.png)
