### ISSUE TITLE
Audio Repeat

### ISSUE THREAD

**Issue by crockwave** [puemos/radiopush#4]
The audio player needs to offer a Repeat mode, inserting `autoplay loop` into the `audio` element when repeat is enabled

`<audio src="sound.mp3" autoplay loop></audio>`

**Comment by obsidienne** [comment]
I'm not sure to understand the issue. 

Why do you want to add loop ? We only have an audio preview of the song.

**Comment by crockwave** [comment]
You know your market better than I do.  However, in some cases, it might add more value if someone enjoys a particular song and chooses to place that song on repeat.  One specific use case is when someone would like to focus on a task, repeating the same song improves that focus.  Also, it is relatively simple to offer a Repeat icon and to insert `autoplay loop`.

**Comment by puemos** [comment]
Thanks for your answer @crockwave, much appreciated.
At the moment I'd like to maintain the simplest UX possible, if we will see more users ask for this I will reconsider :)
