### ISSUE TITLE
Add metadata

### ISSUE THREAD

**Issue by obsidienne** [puemos/radiopush#6]
It's interesting to display the following data

- [x] [explicit](https://developer.spotify.com/documentation/web-api/reference/#object-trackobject)
- [x] [tempo](https://developer.spotify.com/documentation/web-api/reference/#object-audiofeaturesobject)
- [x] duration
- [ ] kind (salsa, pop, rock, ...)

**Comment by obsidienne** [comment]
@puemos do you have an idea on where to display those metadata ? 
It will be a mess if I show every thing

**Comment by puemos** [comment]
![image](https://user-images.githubusercontent.com/13174025/121340867-5bba3b00-c920-11eb-9f7f-baaf6704d024.png)

Options:
1. Under the image, a new raw
2. Under the album name

**Comment by puemos** [comment]
Any thoughts?

**Comment by obsidienne** [comment]
Under the album name but aligned with the lower border of the song art. 
Using a gray light color

**Comment by obsidienne** [comment]
I will not add song kind in the PR, it's way more complex than adding tempo or duration.
As the api does not provide the kind at the song level, I will create another issue/PR to follow the dev
